name: Action Regex Match
description: Match a input text with a input regex.
author: SettingDust
inputs:
  text:
    description: A text as the target for inputs.regex.
    required: true
  regex:
    description: A regex for inputs.text. Supports capturing groups.
    required: true
  flags:
    description: Flags for inputs.regex. e.g.) 'g', 'gm'
    required: false
outputs:
  matches:
    description: All captured group split with line breaks.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: search
  color: yellow
